### ISSUE TITLE
Please replace #define swap()

### ISSUE THREAD

**Issue by ScruffR** [pkourany/Adafruit_mfGFX_IDE#1]
That macro makes the use of several std:: classes rather difficult.

This rather simple test throws a load of errors all in `std::vector`

``` cpp
#include "Adafruit_mfGFX/Adafruit_mfGFX.h"
#include <vector>
void setup() { }
void loop() { }
```

Sure `#undef swap` does fix that, but still ;-)

**Comment by pkourany** [comment]
@ScruffR, the question is why does the swap macro cause issues?  It would be very simple to wrap the definition like this:

```
#ifndef swap
#define swap(a, b) { int16_t t = a; a = b; b = t; }
#endif
```

Could you this that a shot?

**Comment by ScruffR** [comment]
The problem seems to be that once `swap` is defined as macro, the `swap` function in `std::vector` and other `std::` containers is hidden by the macro.

On the other hand, if I flip the includes round, any call to `vector::swap` results in an error.
So the only way around this is to rename the swap macro or limit its lifetime to the GFX library only.

BTW, the same issue is presend with the Adafruit_GFX lib.

**Comment by pkourany** [comment]
Then perhaps the best solution is to change swap to swapBytes or something similar.

**Comment by ScruffR** [comment]
Yup, that'd help

**Comment by pkourany** [comment]
Do you want to do a PR?  Otherwise, I'll get to it this weekend.

**Comment by ScruffR** [comment]
I'll see how my home schedule looks like this weekend ;-)
